name: Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "43 5 * * 2"
  branch_protection_rule:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analysis:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      security-events: write # upload SARIF results
      id-token: write # Scorecard publishes results with an OIDC token
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
      - uses: github/codeql-action/upload-sarif@3ea06614dafe36dec890db3446326e0d40ce53d4 # v3.38.1
        with:
          sarif_file: results.sarif
